<section id="banner" class="bg-img">
<!-- src="/img/bg.png" -->
	<div class="inner">
		<header>
			<h1>We Gather Because We Care</h1>
		</header>
	</div>
	<a href="#one" class="more">Learn More</a>
</section>

<!-- One -->
<section id="one" class="wrapper post bg-img">
<!-- data-bg="/img/banner2.jpg" -->
	<div class="inner">
		<article class="box">
			<header>
				<h2>Tangan di atas lebih mulia dari tangan di bawah</h2>
			</header>
			<div class="content">
				<p>Sebagai manusia seyogyanya kita memiliki kewajiban untuk berbuat baik, salah satunya membantu sesama. Berbicara tentang membantu sesama, tentu banyak cara yang bisa dilakukan, dalam bentuk dukungan moril maupun materil</p>
			</div>
			<footer>
				<a href="/donasi" class="button alt">Mulai Donasi</a>
			</footer>
		</article>
	</div>
</section>
