<style>
    h2 {
        text-align: center;
    }
    .dropdown {
        text-align: center;
    }
</style>

<section id="halamanrekap" class="wrapper more bg-img">
	<div class="inner">
		<article>
			<header>
				<h2>Rekap Donasi</h2>
            </header>
            <div class="header_wrap">
                <div class="num_rows">
                    <div class="form-group"> 	<!--		Show Numbers Of Rows 		-->
                        <select class  ="form-control" name="state" id="maxRows"> 
                                <option value="10">10</option>
                                <option value="15">15</option>
                                <option value="20">20</option>
                        </select>
                    </div>
                </div>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Jenis Donasi
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Uang Tunai</a>
                        <a class="dropdown-item" href="#">Makanan</a>
                        <a class="dropdown-item" href="#">Obat</a>
                    </div>
                </div>
            </div>
            <br>
			<div class="content">
                <table class="table table-striped table-class" id= "table-id">
                
                    
                    <thead>
                        <tr>
                            <th>Nama Pendonasi</th>
                            <th>Jenis Donasi</th>
                            <th>Keterangan</th>
                            <th>Jumlah Donasi</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Rajah Armstrong</td>
                            <td>erat.neque@noncursusnon.ca</td>
                            <td>1-636-140-1210</td>
                            <td>Oct 26, 2015</td>
                        </tr>
                        <tr>
                            <td>Kuame Parsons</td>
                            <td>non.sapien@in.com</td>
                            <td>1-962-122-8834</td>
                            <td>Aug 2, 2015</td>
                        </tr>
                        <tr>
                            <td>Ira Parker</td>
                            <td>Vivamus.molestie.dapibus@quisturpisvitae.edu</td>
                            <td>1-584-906-8572</td>
                            <td>Sep 15, 2015</td>
                        </tr>
                        <tr>
                            <td>Dante Carlson</td>
                            <td>dis.parturient@mi.co.uk</td>
                            <td>1-364-156-9666</td>
                            <td>Nov 28, 2015</td>
                        </tr>
                        <tr>
                            <td>Nathan Bernard</td>
                            <td>Etiam.vestibulum.massa@nonummy.net</td>
                            <td>1-646-420-3211</td>
                            <td>Aug 4, 2016</td>
                        </tr>
                        <tr>
                            <td>Dillon Poole</td>
                            <td>eget@vitae.ca</td>
                            <td>1-788-762-3800</td>
                            <td>Apr 25, 2016</td>
                        </tr>
                        <tr>
                            <td>Hu Leach</td>
                            <td>ligula.eu.enim@eu.org</td>
                            <td>1-888-617-5106</td>
                            <td>Nov 3, 2015</td>
                        </tr>
                        <tr>
                            <td>Dean Lucas</td>
                            <td>ligula.Nullam.feugiat@orciUt.org</td>
                            <td>1-176-725-3287</td>
                            <td>Mar 10, 2016</td>
                        </tr>
                        <tr>
                            <td>Dorian Durham</td>
                            <td>at@conubianostraper.org</td>
                            <td>1-867-829-4207</td>
                            <td>Nov 11, 2016</td>
                        </tr>
                        <tr>
                            <td>Roth Ward</td>
                            <td>Donec@atvelitCras.ca</td>
                            <td>1-539-674-6286</td>
                            <td>May 4, 2015</td>
                        </tr>
                        <tr>
                            <td>Geoffrey Gilliam</td>
                            <td>rutrum.justo.Praesent@euismodetcommodo.ca</td>
                            <td>1-450-585-0087</td>
                            <td>Nov 28, 2016</td>
                        </tr>
                        <tr>
                            <td>Vance Bonner</td>
                            <td>Nunc.mauris@amet.co.uk</td>
                            <td>1-746-842-1533</td>
                            <td>Jul 25, 2016</td>
                        </tr>
                        <tr>
                            <td>Castor Rivera</td>
                            <td>faucibus.Morbi.vehicula@euismodet.edu</td>
                            <td>1-134-497-7454</td>
                            <td>Dec 3, 2016</td>
                        </tr>
                        <tr>
                            <td>Marshall Wheeler</td>
                            <td>tempus.eu@sedfacilisis.ca</td>
                            <td>1-709-608-3138</td>
                            <td>Dec 6, 2015</td>
                        </tr>
                        <tr>
                            <td>Porter Woods</td>
                            <td>ultricies.sem.magna@urnajustofaucibus.com</td>
                            <td>1-797-194-5400</td>
                            <td>Jul 21, 2016</td>
                        </tr>
                        <tr>
                            <td>Dexter Barnes</td>
                            <td>convallis@auctorveliteget.org</td>
                            <td>1-262-180-8026</td>
                            <td>Sep 1, 2016</td>
                        </tr>
                        <tr>
                            <td>Aaron Owen</td>
                            <td>rhoncus.Nullam.velit@luctusutpellentesque.net</td>
                            <td>1-236-283-7422</td>
                            <td>Jul 26, 2016</td>
                        </tr>
                        <tr>
                            <td>Malachi Mcmahon</td>
                            <td>nunc.sed.pede@Maurisblanditenim.com</td>
                            <td>1-973-844-7994</td>
                            <td>Dec 31, 2015</td>
                        </tr>
                        <tr>
                            <td>Ivan Vasquez</td>
                            <td>eu.lacus.Quisque@Nunc.org</td>
                            <td>1-626-851-7695</td>
                            <td>Feb 23, 2016</td>
                        </tr>
                        <tr>
                            <td>Colby Cline</td>
                            <td>faucibus.orci.luctus@VivamusnisiMauris.com</td>
                            <td>1-861-773-5057</td>
                            <td>Nov 11, 2015</td>
                        </tr>
                        <tr>
                            <td>Dale Crawford</td>
                            <td>ac@estacmattis.ca</td>
                            <td>1-620-744-5242</td>
                            <td>Oct 8, 2016</td>
                        </tr>
                        <tr>
                            <td>Griffith Flowers</td>
                            <td>Ut.tincidunt@tellus.ca</td>
                            <td>1-690-390-5508</td>
                            <td>Sep 12, 2015</td>
                        </tr>
                    <tbody>
                </table>

                <!-- Start Pagination -->
                <div class='pagination-container'>
                    <nav>
                    <ul class="pagination">
                    <!--	Here the JS Function Will Add the Rows -->
                    </ul>
                    </nav>
                </div>
                <div class="rows_count">
                    Showing 11 to 20 of 91 entries
                </div>
            </div>
        </article>
    </div>
</section>
      
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

<script type="text/javascript">
getPagination('#table-id');
	$('#maxRows').trigger('change');
	function getPagination (table){

		  $('#maxRows').on('change',function(){
		  	$('.pagination').html('');						// reset pagination div
		  	var trnum = 0 ;									// reset tr counter 
		  	var maxRows = parseInt($(this).val());			// get Max Rows from select option
        
		  	var totalRows = $(table+' tbody tr').length;		// numbers of rows 
			 $(table+' tr:gt(0)').each(function(){			// each TR in  table and not the header
			 	trnum++;									// Start Counter 
			 	if (trnum > maxRows ){						// if tr number gt maxRows
			 		
			 		$(this).hide();							// fade it out 
			 	}if (trnum <= maxRows ){$(this).show();}// else fade in Important in case if it ..
			 });											//  was fade out to fade it in 
			 if (totalRows > maxRows){						// if tr total rows gt max rows option
			 	var pagenum = Math.ceil(totalRows/maxRows);	// ceil total(rows/maxrows) to get ..  
			 												//	numbers of pages 
			 	for (var i = 1; i <= pagenum ;){			// for each page append pagination li 
			 	$('.pagination').append('<li data-page="'+i+'">\
								      <span>'+ i++ +'<span class="sr-only">(current)</span></span>\
								    </li>').show();
			 	}											// end for i 
     
         
			} 												// end if row count > max rows
			$('.pagination li:first-child').addClass('active'); // add active class to the first li 
        
        
        //SHOWING ROWS NUMBER OUT OF TOTAL DEFAULT
       showig_rows_count(maxRows, 1, totalRows);
        //SHOWING ROWS NUMBER OUT OF TOTAL DEFAULT

        $('.pagination li').on('click',function(e){		// on click each page
        e.preventDefault();
				var pageNum = $(this).attr('data-page');	// get it's number
				var trIndex = 0 ;							// reset tr counter
				$('.pagination li').removeClass('active');	// remove active class from all li 
				$(this).addClass('active');					// add active class to the clicked 
        
        
        //SHOWING ROWS NUMBER OUT OF TOTAL
       showig_rows_count(maxRows, pageNum, totalRows);
        //SHOWING ROWS NUMBER OUT OF TOTAL
        
        
        
				 $(table+' tr:gt(0)').each(function(){		// each tr in table not the header
				 	trIndex++;								// tr index counter 
				 	// if tr index gt maxRows*pageNum or lt maxRows*pageNum-maxRows fade if out
				 	if (trIndex > (maxRows*pageNum) || trIndex <= ((maxRows*pageNum)-maxRows)){
				 		$(this).hide();		
				 	}else {$(this).show();} 				//else fade in 
				 }); 										// end of for each tr in table
					});										// end of on click pagination list
		});
											// end of on select change 
		 
								// END OF PAGINATION 
    
	}	

    // SI SETTING
    $(function(){
        // Just to append id number for each row  
    default_index();
                        
    });

    //ROWS SHOWING FUNCTION
    function showig_rows_count(maxRows, pageNum, totalRows) {
    //Default rows showing
            var end_index = maxRows*pageNum;
            var start_index = ((maxRows*pageNum)- maxRows) + parseFloat(1);
            var string = 'Showing '+ start_index + ' to ' + end_index +' of ' + totalRows + ' entries';               
            $('.rows_count').html(string);
    }

    // CREATING INDEX
    function default_index() {
    $('table tr:eq(0)').prepend('<th> ID </th>')

                        var id = 0;

                        $('table tr:gt(0)').each(function(){	
                            id++
                            $(this).prepend('<td>'+id+'</td>');
                        });
    }

    // All Table search script
    function FilterkeyWord_all_table() {
    
    // Count td if you want to search on all table instead of specific column

    var count = $('.table').children('tbody').children('tr:first-child').children('td').length; 

            // Declare variables
    var input, filter, table, tr, td, i;
    input = document.getElementById("search_input_all");
    var input_value =     document.getElementById("search_input_all").value;
            filter = input.value.toLowerCase();
    if(input_value !=''){
            table = document.getElementById("table-id");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 1; i < tr.length; i++) {
            
            var flag = 0;
            
            for(j = 0; j < count; j++){
                td = tr[i].getElementsByTagName("td")[j];
                if (td) {
                
                    var td_text = td.innerHTML;  
                    if (td.innerHTML.toLowerCase().indexOf(filter) > -1) {
                    //var td_text = td.innerHTML;  
                    //td.innerHTML = 'shaban';
                    flag = 1;
                    } else {
                    //DO NOTHING
                    }
                }
                }
            if(flag==1){
                        tr[i].style.display = "";
            }else {
                tr[i].style.display = "none";
            }
            }
        }else {
        //RESET TABLE
        $('#maxRows').trigger('change');
        }
    }
</script>