<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Aplikasi Phalcon Pendataan Bantuan</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/> -->
        <link rel="stylesheet" href="/css/main.css" />
    </head>
    <body>
            <!-- Header -->
			<header id="header">
				<div class="logo"><a href="index.html">Pendataan Bantuan <span>COVID-19</span></a></div>
				<a href="#menu"><span>Menu</span></a>
			</header>

		    <!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="index.html">Home</a></li>
					<li><a href="/donasi">Mulai Donasi</a></li>
					<li><a href="/rekap">Lihat Rekap Donasi</a></li>
				</ul>
			</nav>
            <?php echo $this->getContent(); ?>

        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <script src="/js/jquery.min.js"></script>
        <script src="/js/jquery.scrolly.min.js"></script>
        <script src="/js/jquery.scrollex.min.js"></script>
        <script src="/js/skel.min.js"></script>
        <script src="/js/util.js"></script>
        <script src="/js/main.js"></script>

        <!-- <script src="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css"></script> -->

        <!-- tabell -->
        <!-- <link href="/assets/bootstrap.min.css" rel="stylesheet">

        <link href="/assets/datatables.bootstrap4.min.css" rel="stylesheet"> -->
        <!-- Bootstrap core JavaScript -->
        <script src="/assets/jquery.min.js"></script>

        <!-- Page level plugin JavaScript -->
        <script src="/assets/jquery.datatables.min.js"></script>

        <script src="/assets/datatables.bootstrap4.min.js"></script>
        
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <!-- Scripts -->
        
        
    </body>
</html>
